2016-10-11 21:49:16:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py
2016-10-11 21:49:17:No exception in execute_script method.
2016-10-11 21:49:17:Exception in execute_script method: [Errno 2] No such file or directory: ''
2016-10-11 21:49:31:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py
2016-10-11 21:49:31:No exception in execute_script method.
2016-10-11 21:49:31:Exception in execute_script method: [Errno 2] No such file or directory: ''
2016-10-11 21:50:08:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py
2016-10-11 21:50:09:No exception in execute_script method.
2016-10-11 21:50:09:Exception in execute_script method: [Errno 2] No such file or directory: ''
2016-10-11 21:51:02:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py
2016-10-11 21:51:03:No exception in execute_script method.
2016-10-11 21:51:03:Exception in execute_script method: [Errno 2] No such file or directory: ''
2016-10-11 21:51:12:execute_script: /Users/tylan/Desktop/myAuty/Auty/scripts/scripts/quanzi/update_user_avatar_test.py
2016-10-11 21:51:13:No exception in execute_script method.
2016-10-11 21:51:13:Exception in execute_script method: [Errno 2] No such file or directory: ''
