2016-09-29 15:00:55:execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 15:00:55:No exception in execute_script method.
2016-09-29 15:00:55:execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 15:00:55:No exception in execute_script method.
2016-09-29 15:00:55:execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 15:00:55:No exception in execute_script method.
2016-09-29 16:25:17execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:25:17No exception in execute_script method.
2016-09-29 16:26:18execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:26:18No exception in execute_script method.
2016-09-29 16:27:46execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:27:46No exception in execute_script method.
2016-09-29 16:28:53execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:28:53No exception in execute_script method.
2016-09-29 16:29:54execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:29:54No exception in execute_script method.
2016-09-29 16:30:57execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:30:57No exception in execute_script method.
2016-09-29 16:47:08execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:47:08No exception in execute_script method.
2016-09-29 16:47:08execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 16:47:08No exception in execute_script method.
2016-09-29 16:47:08execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 16:47:08No exception in execute_script method.
2016-09-29 16:47:32execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:47:32No exception in execute_script method.
2016-09-29 16:47:32execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 16:47:32No exception in execute_script method.
2016-09-29 16:47:32execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 16:47:32No exception in execute_script method.
2016-09-29 16:53:26execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:53:26No exception in execute_script method.
2016-09-29 16:53:26execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 16:53:26No exception in execute_script method.
2016-09-29 16:53:26execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 16:53:26No exception in execute_script method.
2016-09-29 16:59:26execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 16:59:26No exception in execute_script method.
2016-09-29 16:59:26execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 16:59:26No exception in execute_script method.
2016-09-29 16:59:26execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 16:59:26No exception in execute_script method.
2016-09-29 17:01:51execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:01:51No exception in execute_script method.
2016-09-29 17:01:51execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:01:51No exception in execute_script method.
2016-09-29 17:01:51execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:01:51No exception in execute_script method.
2016-09-29 17:02:45execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:02:45No exception in execute_script method.
2016-09-29 17:02:45execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:02:45No exception in execute_script method.
2016-09-29 17:02:45execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:02:45No exception in execute_script method.
2016-09-29 17:03:37execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:03:37No exception in execute_script method.
2016-09-29 17:03:37execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:03:37No exception in execute_script method.
2016-09-29 17:03:37execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:03:37No exception in execute_script method.
2016-09-29 17:05:57execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:05:57No exception in execute_script method.
2016-09-29 17:05:57execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:05:57No exception in execute_script method.
2016-09-29 17:05:57execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:05:57No exception in execute_script method.
2016-09-29 17:12:58execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:12:58No exception in execute_script method.
2016-09-29 17:12:58execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:12:59No exception in execute_script method.
2016-09-29 17:12:59execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:12:59No exception in execute_script method.
2016-09-29 17:16:15execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:16:15No exception in execute_script method.
2016-09-29 17:16:15execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:16:15No exception in execute_script method.
2016-09-29 17:16:15execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:16:15No exception in execute_script method.
2016-09-29 17:18:10execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:18:10No exception in execute_script method.
2016-09-29 17:18:10execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:18:10No exception in execute_script method.
2016-09-29 17:18:10execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:18:10No exception in execute_script method.
2016-09-29 17:20:12execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:20:12No exception in execute_script method.
2016-09-29 17:20:12execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:20:12No exception in execute_script method.
2016-09-29 17:20:12execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:20:12No exception in execute_script method.
2016-09-29 17:21:04execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:21:04No exception in execute_script method.
2016-09-29 17:21:04execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:21:04No exception in execute_script method.
2016-09-29 17:21:04execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:21:04No exception in execute_script method.
2016-09-29 17:21:40execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:21:40No exception in execute_script method.
2016-09-29 17:21:40execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:21:40No exception in execute_script method.
2016-09-29 17:21:40execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:21:40No exception in execute_script method.
2016-09-29 17:22:57execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:22:58No exception in execute_script method.
2016-09-29 17:22:58execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:22:58No exception in execute_script method.
2016-09-29 17:22:58execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:22:58No exception in execute_script method.
2016-09-29 17:24:06execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:24:06No exception in execute_script method.
2016-09-29 17:24:06execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:24:06No exception in execute_script method.
2016-09-29 17:24:06execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:24:06No exception in execute_script method.
2016-09-29 17:24:45execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/1.py
2016-09-29 17:24:45No exception in execute_script method.
2016-09-29 17:24:45execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp1/temp2/1.py
2016-09-29 17:24:45No exception in execute_script method.
2016-09-29 17:24:45execute_script: /Users/tylan/Desktop/Auty/scripts/scripts/temp3/1.py
2016-09-29 17:24:45No exception in execute_script method.
